In [1]:
import numpy as np

1. Sorting - argsort
2. Matrix Slicing
3. linspace
4. matplotlib


In [2]:
a = np.array([42,84, 21, 100, 387, 94, 0, 14, 98, 6])

In [3]:
a

array([ 42,  84,  21, 100, 387,  94,   0,  14,  98,   6])

In [5]:
sorted_index = np.argsort(a)

In [6]:
a[sorted_index]

array([  0,   6,  14,  21,  42,  84,  94,  98, 100, 387])

## matrix slicing 

In [7]:
mat = [[1,2,3,4],[40,50,60,70],[100, 200, 300, 400],[15, 25,35,45]]

In [8]:
mat = np.array(mat)

In [9]:
mat

array([[  1,   2,   3,   4],
       [ 40,  50,  60,  70],
       [100, 200, 300, 400],
       [ 15,  25,  35,  45]])

In [10]:
a

array([ 42,  84,  21, 100, 387,  94,   0,  14,  98,   6])

In [11]:
a[2:6]

array([ 21, 100, 387,  94])

In [12]:
mat

array([[  1,   2,   3,   4],
       [ 40,  50,  60,  70],
       [100, 200, 300, 400],
       [ 15,  25,  35,  45]])

In [17]:
mat[0:3]

array([[  1,   2,   3,   4],
       [ 40,  50,  60,  70],
       [100, 200, 300, 400]])

In [18]:
mat[:,0:3]

array([[  1,   2,   3],
       [ 40,  50,  60],
       [100, 200, 300],
       [ 15,  25,  35]])

In [19]:
mat[0:3,0:3]

array([[  1,   2,   3],
       [ 40,  50,  60],
       [100, 200, 300]])

In [22]:
mat[:,:]

array([[  1,   2,   3,   4],
       [ 40,  50,  60,  70],
       [100, 200, 300, 400],
       [ 15,  25,  35,  45]])

In [24]:
mat[:,:1]

array([[  1],
       [ 40],
       [100],
       [ 15]])

In [26]:
mat[:,:1].reshape(1,4)

array([[  1,  40, 100,  15]])

In [27]:
mat[:,:1].reshape(2,2)

array([[  1,  40],
       [100,  15]])

# linspace

In [32]:
np.linspace(1,40, 6)

array([  1. ,   8.8,  16.6,  24.4,  32.2,  40. ])

In [33]:
np.linspace(1,40, 60)

array([  1.        ,   1.66101695,   2.3220339 ,   2.98305085,
         3.6440678 ,   4.30508475,   4.96610169,   5.62711864,
         6.28813559,   6.94915254,   7.61016949,   8.27118644,
         8.93220339,   9.59322034,  10.25423729,  10.91525424,
        11.57627119,  12.23728814,  12.89830508,  13.55932203,
        14.22033898,  14.88135593,  15.54237288,  16.20338983,
        16.86440678,  17.52542373,  18.18644068,  18.84745763,
        19.50847458,  20.16949153,  20.83050847,  21.49152542,
        22.15254237,  22.81355932,  23.47457627,  24.13559322,
        24.79661017,  25.45762712,  26.11864407,  26.77966102,
        27.44067797,  28.10169492,  28.76271186,  29.42372881,
        30.08474576,  30.74576271,  31.40677966,  32.06779661,
        32.72881356,  33.38983051,  34.05084746,  34.71186441,
        35.37288136,  36.03389831,  36.69491525,  37.3559322 ,
        38.01694915,  38.6779661 ,  39.33898305,  40.        ])

In [34]:
x = np.linspace(0,90,100)

In [37]:
x

array([  0.        ,   0.90909091,   1.81818182,   2.72727273,
         3.63636364,   4.54545455,   5.45454545,   6.36363636,
         7.27272727,   8.18181818,   9.09090909,  10.        ,
        10.90909091,  11.81818182,  12.72727273,  13.63636364,
        14.54545455,  15.45454545,  16.36363636,  17.27272727,
        18.18181818,  19.09090909,  20.        ,  20.90909091,
        21.81818182,  22.72727273,  23.63636364,  24.54545455,
        25.45454545,  26.36363636,  27.27272727,  28.18181818,
        29.09090909,  30.        ,  30.90909091,  31.81818182,
        32.72727273,  33.63636364,  34.54545455,  35.45454545,
        36.36363636,  37.27272727,  38.18181818,  39.09090909,
        40.        ,  40.90909091,  41.81818182,  42.72727273,
        43.63636364,  44.54545455,  45.45454545,  46.36363636,
        47.27272727,  48.18181818,  49.09090909,  50.        ,
        50.90909091,  51.81818182,  52.72727273,  53.63636364,
        54.54545455,  55.45454545,  56.36363636,  57.27

In [35]:
y = np.sin(x)

In [40]:
y = x**x * np.e / np.pi

In [41]:
y

array([  8.65255979e-001,   7.93441470e-001,   2.56573883e+000,
         1.33504300e+001,   9.46095144e+001,   8.43591944e+002,
         9.03291019e+003,   1.12624592e+005,   1.59968354e+006,
         2.54633711e+007,   4.48493922e+008,   8.65255979e+009,
         1.81331964e+011,   4.09961811e+012,   9.94060248e+013,
         2.57221331e+015,   7.07199042e+016,   2.05810847e+018,
         6.31877035e+019,   2.04052653e+021,   6.91259581e+022,
         2.45069336e+024,   9.07286654e+025,   3.50067916e+027,
         1.40517786e+029,   5.85821893e+030,   2.53277517e+032,
         1.13400912e+034,   5.25124779e+035,   2.51195552e+037,
         1.23987620e+039,   6.30823089e+040,   3.30502657e+042,
         1.78148533e+044,   9.87086956e+045,   5.61749121e+047,
         3.28103831e+049,   1.96538956e+051,   1.20658498e+053,
         7.58679244e+054,   4.88295830e+056,   3.21498674e+058,
         2.16424240e+060,   1.48879128e+062,   1.04603029e+064,
         7.50288875e+065,   5.49145084e+