In [2]:
import numpy as np

## Solving Linear Systems

A system of linear equations can be converted to matrix form by deciding on a fixed order of the variables, and using the coefficients of each equation as the elements of a row of the matrix. Thus the system of equations <br>
$x + 3y + 2z = 4$ <br>
$2x - y + z = 1$ <br>
$3x + y - 2z = 2$ <br>
can be represented by the matrix-vector multiplication as <br>
```
 [1.0   3.0   2.0]   [4.0]
 [2.0  -1.0   1.0]   [1.0]
 [3.0   1.0  -2.0]   [2.0]
```

    Writing the same matrix and vector in numpy 

In [3]:
matrix = np.array([[1.0, 3.0, 2.0], [2.0, -1.0, 1.0], [3.0, 1.0, -2.0]])

In [4]:
vector = np.array([4.0, 1.0, 2.0])

In [5]:
vector

array([4., 1., 2.])

In [8]:
vector = vector.reshape(3,1)

In [9]:
vector

array([[4.],
       [1.],
       [2.]])

    The linear algebra functions in numpy are under the np.linalg library
    
Here, to solve the above equation we will use `np.linalg.solve`

In [10]:
np.linalg.solve(matrix, vector)

array([[0.6875],
       [0.8125],
       [0.4375]])

## Raising power of a square matrix

In [11]:
np.linalg.matrix_power(matrix, 3)

array([[ 20.,  38.,  26.],
       [ 22.,   2.,  12.],
       [ 44.,   2., -18.]])

In [12]:
np.linalg.matrix_power(matrix, 100)

array([[1.32529433e+58, 9.50566836e+57, 6.17459355e+57],
       [7.14970569e+57, 5.12812547e+57, 3.33107481e+57],
       [8.04300014e+57, 5.76885517e+57, 3.74727495e+57]])

## Eigenvalues and Eigenvectors

In [15]:
np.linalg.eigvals(matrix)

array([ 3.83221165, -3.3077737 , -2.52443796])

.

    More reference: https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.linalg.html