In [1]:
import numpy as np

In [4]:
np.ones([6,6])

array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

In [38]:
group = [[1,2,3,4,5,6], [2, 0, 0, 0, 0, 0],[3,0,0,0,0,0],[4,0,0,0,0,0], [4,0,0,0,0,0], [5,0,0,0,0,0], [6,0,0,0,0,0]]

In [39]:
mat = np.array(group)

In [40]:
mat[]

array([[1, 2, 3, 4, 5, 6],
       [2, 0, 0, 0, 0, 0],
       [3, 0, 0, 0, 0, 0],
       [4, 0, 0, 0, 0, 0],
       [4, 0, 0, 0, 0, 0],
       [5, 0, 0, 0, 0, 0],
       [6, 0, 0, 0, 0, 0]])

In [34]:
mat[:1,1:2]

array([[2]])

In [44]:
mat[1:,2:]

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [26]:
range(1,7)[-1]

6

In [45]:
a = range(1,-7)
for m in mat[1:,2:]:
    m[0] = 1
    if m[0] in mat[:1,1:2]:
        m[0] = 1+1

In [46]:
mat

array([[1, 2, 3, 4, 5, 6],
       [2, 1, 1, 0, 0, 0],
       [3, 1, 1, 0, 0, 0],
       [4, 1, 1, 0, 0, 0],
       [4, 1, 1, 0, 0, 0],
       [5, 1, 1, 0, 0, 0],
       [6, 1, 1, 0, 0, 0]])